CREATE TABLE STATS (
    STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLER_COUNT AS
SELECT COUNT(*) AS BESTSELLER_COUNT
FROM BOOKS WHERE BESTSELLER = 1;

DELIMITER $$
CREATE EVENT IF NOT EXISTS EV_UPDATE_BESTSELLERS
ON SCHEDULE EVERY 1 minute
DO
BEGIN
    CALL UpdateBestsellers();
    INSERT INTO STATS (STAT_DATE, STAT, VALUE)
    SELECT NOW(), 'BESTSELLERS', BESTSELLER_COUNT
    FROM BESTSELLER_COUNT;
    
END $$
DELIMITER ;