EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'Marissa' and LASTNAME = 'Cain';

CREATE INDEX IDX_READERS_NAME ON READERS(FIRSTNAME, LASTNAME);

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'Marissa' and LASTNAME = 'Cain';

EXPLAIN SELECT * FROM BOOKS WHERE TITLE = 'Gone with the wind';

CREATE INDEX BOOKS_TITLE ON BOOKS(TITLE);

EXPLAIN SELECT * FROM BOOKS WHERE TITLE = 'Gone with the wind';

