CREATE TABLE BOOKS_AUD (
    EVENT_ID INT(11) NOT NULL auto_increment,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_TYPE VARCHAR(10) DEFAULT NULL,
    BOOK_ID INT(11) NOT NULL,
    BOOK_TITLE VARCHAR(255),
    NEW_TITLE VARCHAR(255) DEFAULT NULL,
    NEW_PUBYEAR INT(11) DEFAULT NULL,
    NEW_BESTSELLER TINYINT(1) DEFAULT NULL,
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE READERS_AUD (
    EVENT_ID INT(11) NOT NULL auto_increment,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_TYPE VARCHAR(10) DEFAULT NULL,
    READER_ID INT(11) NOT NULL,
    NEW_FIRSTNAME VARCHAR(255) DEFAULT NULL,
    NEW_LASTNAME VARCHAR(255) DEFAULT NULL,
    NEW_VIP_LEVEL VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (EVENT_ID)
);

DELIMITER $$

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS                                      
FOR EACH ROW
BEGIN
   INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, BOOK_TITLE)                               
      VALUES(CURTIME(), "INSERT", NEW.BOOK_ID, NEW.TITLE);                                                           
END $$



CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS                                      
FOR EACH ROW
BEGIN
   INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, BOOK_TITLE, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLER)                               
      VALUES(CURTIME(), "UPDATE", OLD.BOOK_ID, OLD.TITLE, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLER);                                                           
END $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS                                      
FOR EACH ROW
BEGIN
   INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, BOOK_TITLE)                               
      VALUES(CURTIME(), "DELETE", OLD.BOOK_ID, OLD.TITLE);                                                           
END $$

DELIMITER ;

INSERT INTO BOOKS (TITLE, PUBYEAR, BESTSELLER)
VALUES ('The Test Book', 2023, 1);

DELIMITER $$

CREATE TRIGGER READERS_INSERT AFTER INSERT ON READERS                                    
FOR EACH ROW
BEGIN
   INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID)                               
      VALUES(CURTIME(), "INSERT", NEW.READER_ID);                                                           
END $$



CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS                                      
FOR EACH ROW
BEGIN
   INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_VIP_LEVEL)                               
      VALUES(CURTIME(), "UPDATE", OLD.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.VIP_LEVEL);                                                           
END $$

CREATE TRIGGER READERS_DELETE AFTER DELETE ON READERS                                      
FOR EACH ROW
BEGIN
   INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID)                               
      VALUES(CURTIME(), "DELETE", OLD.READER_ID);                                                           
END $$

DELIMITER ;

INSERT INTO READERS (FIRSTNAME, LASTNAME, PESELID, VIP_LEVEL)
VALUES ('Alice', 'Smith', '7236827342', 'Gold');

UPDATE READERS
SET FIRSTNAME = 'Alicia',
    LASTNAME = 'Smith-Jones',
    VIP_LEVEL = 'Platinum'
WHERE READER_ID = 1;

DELETE FROM READERS
WHERE READER_ID = 1;