ALTER TABLE books
ADD COLUMN BESTSELLER BOOLEAN DEFAULT 0;

DROP PROCEDURE IF EXISTS UpdateBestsellers;
DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE BOOK_ID INT;
    DECLARE RENT_COUNT INT DEFAULT 0;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE PROC_DONE INT DEFAULT 0;

    DECLARE book_cursor CURSOR FOR
        SELECT BOOK_ID FROM BOOKS;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;

    SET PROC_DONE = 0;

    OPEN book_cursor;

    WHILE (FINISHED = 0) DO
        FETCH book_cursor INTO BOOK_ID;

        IF (FINISHED = 0) THEN
            SELECT COUNT(*) INTO RENT_COUNT
            FROM RENTS
            WHERE BOOK_ID = BOOK_ID
              AND RENT_DATE >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH);

            IF RENT_COUNT > 2 THEN
                UPDATE BOOKS SET BESTSELLER = TRUE WHERE BOOK_ID = BOOK_ID;
            ELSE
                UPDATE BOOKS SET BESTSELLER = FALSE WHERE BOOK_ID = BOOK_ID;
            END IF;

            COMMIT;
        END IF;
    END WHILE;

    CLOSE book_cursor;

    SET PROC_DONE = 1;
    SELECT PROC_DONE AS PROCEDURE_STATUS;
END $$
DELIMITER ;

CALL UpdateBestsellers();
SELECT * FROM books;