ALTER TABLE books
ADD COLUMN BESTSELLER BOOLEAN DEFAULT 0;

DROP PROCEDURE IF EXISTS UpdateBestsellers;
DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE BOOK_ID INT;
    DECLARE RENT_COUNT INT;
    DECLARE DONE INT DEFAULT 0;

    DECLARE book_cursor CURSOR FOR
        SELECT BOOK_ID FROM BOOKS;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;

    OPEN book_cursor;

    read_loop: LOOP
        FETCH book_cursor INTO BOOK_ID;

        IF DONE = 1 THEN
            LEAVE read_loop;
        END IF;

        SELECT COUNT(*) INTO RENT_COUNT
        FROM RENTS
        WHERE BOOK_ID = BOOK_ID
            AND RENT_DATE >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH);

        IF RENT_COUNT > 2 THEN
            UPDATE BOOKS SET BESTSELLER = TRUE WHERE BOOK_ID = BOOK_ID;
        ELSE
            UPDATE BOOKS SET BESTSELLER = FALSE WHERE BOOK_ID = BOOK_ID;
        END IF;
    END LOOP;

    CLOSE book_cursor;
END $$
DELIMITER ;
SELECT * FROM books;